version: 2
jobs:
  build:
    machine:
      image: circleci/openjdk:11-jdk-buster
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - maven-repo-v1-{{ checksum "pom.xml" }}
            - maven-repo-v1-
      - run:
          name: Test
          command: |
            mvn test
      - store_artifacts:
          path: target/my-reports
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ checksum "pom.xml" }}
          
